suppressPackageStartupMessages({
  library(BiocParallel)
  library(dplyr)
  library(SingleCellExperiment)
  library(scater)
  library(scran)
  library(Seurat)
  library(Matrix)
  library(Hmisc)  
  library(batchelor)
  library(reshape2)
  library(ggplot2)

})
source("PhenoAligner_functions.R")

# mph <-readRDS("processed_data/data_B2-19/cell_typing/myeloid/myeloid.batch.corrected_ct_1.5.rds")
mph <-readRDS("plots/data/myeloid_new_meta.rds")

DefaultAssay(mph) <- "RNA"
unique(mph$LN_condition)

# mph$subtype1 <- mph$cell_type1

unique(mph$subtype1)

# read markers for each subtype
mph_marker <- read.csv("processed_data/data_B2-19/cell_typing/myeloid/myeloid.batch.corrected.markers.1.5.csv")
#select gene set(here we used marker genes generated by Seurat FindAllMarkers() function)
mph_marker <- mph_marker[mph_marker$p_val_adj < 0.05,]  
mph_marker <- as.character(unique(mph_marker$gene)) 
length(mph_marker)

#run for PhenoAligner index
PA_knn_results <- PhenoAligner_KNN(mph,mph_marker,cell_type="mph")

pheno_result <- PhenoAligner_index(PA_knn_results$sce.others, PA_knn_results$sce.mt, PA_knn_results$coldata.mt, 
                               cell_type="mph", cor_cutoff=0.6)

pheno_shuffle.list <- PhenoAligner_shuffle(sce.others <- PA_knn_results$sce.others,
                     sce.mt <- PA_knn_results$sce.mt,
                     cell_type="mph",threads=20)

mph_plot_pheno_list <- plot_pheno(pheno_result,pheno_shuffle.list,cell_type="mph")

names(mph_plot_pheno_list)



for(subtype in names(mph_plot_pheno_list)){
    mph_plot_pheno_list[[subtype]]$celltype_sub <- subtype
}
plot_subtypes_df <- do.call(rbind, mph_plot_pheno_list)

options(repr.plot.width=10, repr.plot.height=11)
p_mph <- ggplot(plot_subtypes_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 2)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 5) +
  facet_wrap(. ~  celltype_sub, ncol = 4) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_mph)   

tcell <-readRDS("plots/data/tcell_no_TLB_new_meta.rds")

# Idents(tcell) <- "subtype1"
# tcell.markers <- FindAllMarkers(tcell, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

# write.csv(tcell.markers, "processed_data/data_B2-19/cell_typing/tcell/tcell.global.subtype1_markers.csv")

tcell.markers <- read.csv("processed_data/data_B2-19/cell_typing/tcell/tcell.global.subtype1_markers.csv",row.names=1)

tcell_marker <- tcell.markers[tcell.markers$p_val_adj < 0.05,] # not sure 
tcell_marker <- as.character(unique(tcell_marker$gene)) 
length(tcell_marker)

table(tcell$subtype1)

dim(tcell)

# subset big subtype to 2000 cells
set.seed=0
tcell_use <- NULL
for(subtype in unique(tcell$subtype1)){
    print(subtype)
    print(sum(tcell$subtype1==subtype))
    if(sum(tcell$subtype1==subtype) > 2000){
        rowname <- sample(colnames(tcell)[tcell$subtype1==subtype], 2000, replace = FALSE)
    }else{
        rowname <- colnames(tcell)[tcell$subtype1==subtype]
    }
    tcell_use <- c(tcell_use,rowname)
    print(length(rowname))
}

length(tcell_use)

tcell <- subset(tcell,cells=tcell_use)

#run for PhenoAligner index
tcell_PA_knn_results <- PhenoAligner_KNN(tcell,tcell_marker,cell_type="tcell")

tcell_pheno_result <- PhenoAligner_index(tcell_PA_knn_results$sce.others, tcell_PA_knn_results$sce.mt, tcell_PA_knn_results$coldata.mt, 
                               cell_type="tcell", cor_cutoff=0.6)

tcell_pheno_shuffle.list <- PhenoAligner_shuffle(sce.others <- tcell_PA_knn_results$sce.others,
                     sce.mt <- tcell_PA_knn_results$sce.mt,
                     cell_type="tcell",threads=20)

tcell_plot_pheno_list <- plot_pheno(tcell_pheno_result,tcell_pheno_shuffle.list,cell_type="tcell")

# tcell_plot_pheno_list <- readRDS(paste0("processed_data/data_B2-19/PhenoAligner/", "tcell", "/plots.list.rds"))

names(tcell_plot_pheno_list)

for(subtype in names(tcell_plot_pheno_list)){
    tcell_plot_pheno_list[[subtype]]$celltype_sub <- subtype
}
plot_subtypes_df <- do.call(rbind, tcell_plot_pheno_list)

options(repr.plot.width=12, repr.plot.height=12)
p_tcell <- ggplot(plot_subtypes_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 2)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 5) +
  facet_wrap(. ~  celltype_sub, ncol = 5) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_tcell)   

# tcell_plot_pheno_list <- readRDS("processed_data/data_B2-19/PhenoAligner/tcell/plots.list.rds")


my_colors5=c("#DAC5DF","#BBD5EB","#6C8DC1","#EAAB9E","#DD6E60")

plot_subtypes_nk_df <- plot_subtypes_df[plot_subtypes_df$celltype_sub %in% c("NK1","NK2","NK3"),]
plot_subtypes_nk_df$Tissue <-  factor(plot_subtypes_nk_df$Tissue,levels=c("Adj.Nor", "Pri.GC", "Met.LN", "Neg.LN", "PBMC"))

my_colors4 <- my_colors5[c(1:2,4:5)]

options(repr.plot.width=9, repr.plot.height=3)
p_nk <- ggplot(plot_subtypes_nk_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
        scale_fill_manual(values = my_colors4) +
  geom_point(aes(y = I_phenoaligner), size = 0.7)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 6) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_nk)   
ggsave(p_nk,file="plots/figures/figS4E_NK_pheno.pdf",width=9, height=3)

# color optional
plot_subtypes_nk_df <- plot_subtypes_df[plot_subtypes_df$celltype_sub %in% c("NK1","NK2","NK3"),]
plot_subtypes_nk_df$Tissue <-  factor(plot_subtypes_nk_df$Tissue,levels=c("Adj.Nor", "Pri.GC", "Met.LN", "Neg.LN", "PBMC"))

options(repr.plot.width=9, repr.plot.height=3)
p_tcell_2 <- ggplot(plot_subtypes_nk_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 0.7)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 6) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_tcell_2)   
# ggsave(p_tcell_2,file="plots//figures/figS4E_NK_pheno.pdf",width=9, height=3)

# not used for boxplot
plot_subtypes_nk_df <- plot_subtypes_df[plot_subtypes_df$celltype_sub %in% c("NK1","NK2","NK3"),]

options(repr.plot.width=9, repr.plot.height=3)
p_tcell_2 <- ggplot(plot_subtypes_nk_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_boxplot()+ 
  geom_point(aes(y = I_phenoaligner), size = 0.7)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 2)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 7) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_tcell_2)   

# not used
plot_subtypes_tex_df <- plot_subtypes_df[plot_subtypes_df$celltype_sub %in% c("CD8_TIM3+ Trm","CD8_LAYN+ Tex","CD8_CCL5+ Tex"),]
plot_subtypes_tex_df$Tissue <-  factor(plot_subtypes_tex_df$Tissue,levels=c("Adj.Nor", "Pri.GC", "Met.LN", "Neg.LN", "PBMC"))#

options(repr.plot.width=9, repr.plot.height=3)
p_tcell_2 <- ggplot(plot_subtypes_tex_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 0.7)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 6) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_tcell_2)   

# tcell_plot_pheno_list <- readRDS("processed_data/data_B2-19/PhenoAligner/tcell/plots.list.rds")


# for(subtype in names(tcell_plot_pheno_list)){
#     tcell_plot_pheno_list[[subtype]]$celltype_sub <- subtype
# }
# plot_subtypes_df <- do.call(rbind, tcell_plot_pheno_list)

plot_subtypes_tex_df <- plot_subtypes_df[plot_subtypes_df$celltype_sub %in% c("CD8_TIM3+ Trm","CD8_LAYN+ Tex"),]
plot_subtypes_tex_df$Tissue <-  factor(plot_subtypes_tex_df$Tissue,levels=c("Adj.Nor", "Pri.GC", "Met.LN", "Neg.LN", "PBMC"))#
my_colors4 <- my_colors5[c(1:2,4:5)]#


options(repr.plot.width=7, repr.plot.height=3)
p_tcell_2 <- ggplot(plot_subtypes_tex_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
        scale_fill_manual(values = my_colors4) +#
  geom_point(aes(y = I_phenoaligner), size = 0.7)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 6) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_tcell_2)   
ggsave(p_tcell_2,file="plots/figures/figS2C_tim_tex_pheno.pdf",width=7, height=3)#


plot_subtypes_tex_df <- plot_subtypes_df[plot_subtypes_df$celltype_sub %in% c("CD8_TIM3+ Trm","CD8_LAYN+ Tex"),]
plot_subtypes_tex_df$Tissue <-  factor(plot_subtypes_tex_df$Tissue,levels=c("Adj.Nor", "Pri.GC", "Met.LN", "Neg.LN", "PBMC"))#
# my_colors4 <- my_colors5[c(1:2,4:5)]#


options(repr.plot.width=7, repr.plot.height=3)
p_tcell_2 <- ggplot(plot_subtypes_tex_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
        # scale_fill_manual(values = my_colors4) +#
  geom_point(aes(y = I_phenoaligner), size = 0.7)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 6) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_tcell_2)   
# ggsave(p_tcell_2,file="plots/figures/figS2C_tim_tex_pheno.pdf",width=9, height=3)#


# example plot for one cell type
tmp_df <- tcell_plot_pheno_list[["CD4_Tex"]]
tmp_df$Tissue <-  factor(tmp_df$Tissue,levels=c("Adj.Nor", "Pri.GC", "Met.LN", "Neg.LN", "PBMC"))#
my_colors4 <- my_colors5[c(1:2,4:5)]#

options(repr.plot.width=4, repr.plot.height=3)
p_cd4_tex <- ggplot(tmp_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
        scale_fill_manual(values = my_colors4) +#

  geom_point(aes(y = I_phenoaligner), size = 1)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 6) + #, fontface = "bold"
#   facet_wrap(. ~  celltype_sub, ncol = 5) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p_cd4_tex)  
ggsave(p_cd4_tex,file="plots/figures/fig2G_cd4_tex_pheno.pdf",width=4, height=3)#




bcell <-readRDS("processed_data/data_B2-19/cell_typing/bcell/plasma.batch.corrected_ct_0.5.rds")

bcell_marker <- read.csv("processed_data/data_B2-19/cell_typing/bcell/plasma.corrected.markers_0.5.csv")
#select gene set(here we used marker genes generated by Seurat FindAllMarkers() function)
bcell_marker <- bcell_marker[bcell_marker$p_val_adj < 0.05,] # not sure 
bcell_marker <- as.character(unique(bcell_marker$gene)) 
length(bcell_marker)

bcell$subtype1 <- bcell$cell_type

meta_condition <- read.csv("processed_data/data_B2-19/metadata_all_ct_subtype_condition.csv", row.names = 1)

colnames(bcell@meta.data)

meta <- meta_condition[colnames(bcell),]
all(rownames(meta)==colnames(bcell))
bcell$LN_condition <- meta$LN_condition

table(bcell$cell_type)

unique(bcell$LN_condition)

#run for PhenoAligner index
bcell_PA_knn_results <- PhenoAligner_KNN(bcell,bcell_marker,cell_type="bcell")

bcell_pheno_result <- PhenoAligner_index(bcell_PA_knn_results$sce.others, bcell_PA_knn_results$sce.mt, bcell_PA_knn_results$coldata.mt, 
                               cell_type="bcell", cor_cutoff=0.6)



bcell_pheno_shuffle.list <- PhenoAligner_shuffle(sce.others <- bcell_PA_knn_results$sce.others,
                     sce.mt <- bcell_PA_knn_results$sce.mt,
                     cell_type="bcell",threads=20)

plot_pheno(bcell_pheno_result,bcell_pheno_shuffle.list,cell_type="bcell")



# bcell_pheno_result <- read.csv(paste0("processed_data/data_B2-19/PhenoAligner/tcell/", "bcell", "/PhenoAligner_index_final.csv"))
# bcell_pheno_shuffle.list <- readRDS(paste0("processed_data/data_B2-19/PhenoAligner/", "bcell", "/pheno_shuffle.list.rds"))

bcell_plot_pheno_list <- plot_pheno(bcell_pheno_result,bcell_pheno_shuffle.list,cell_type="bcell")

names(bcell_plot_pheno_list)

bcell_plot_pheno_list$`Low quality` <- NULL
names(bcell_plot_pheno_list)

for(subtype in names(bcell_plot_pheno_list)){
    bcell_plot_pheno_list[[subtype]]$celltype_sub <- subtype
}
plot_subtypes_df <- do.call(rbind, bcell_plot_pheno_list)

options(repr.plot.width=8, repr.plot.height=9)
p <- ggplot(plot_subtypes_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 2)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 5) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p)   



ls()

bcell <-readRDS("processed_data/data_B2-19/cell_typing/bcell/mem_naive.batch.corrected_ct_1.rds")

bcell_marker <- read.csv("processed_data/data_B2-19/cell_typing/bcell/mem_naive.corrected.markers_1.csv")
#select gene set(here we used marker genes generated by Seurat FindAllMarkers() function)
bcell_marker <- bcell_marker[bcell_marker$p_val_adj < 0.05,] # not sure 
bcell_marker <- as.character(unique(bcell_marker$gene)) 
length(bcell_marker)

bcell$subtype1 <- bcell$cell_type

meta_condition <- read.csv("processed_data/data_B2-19/metadata_all_ct_subtype_condition.csv", row.names = 1)

colnames(bcell@meta.data)

meta <- meta_condition[colnames(bcell),]
all(rownames(meta)==colnames(bcell))
bcell$LN_condition <- meta$LN_condition

table(bcell$cell_type)

unique(bcell$LN_condition)

#run for PhenoAligner index
bcell_PA_knn_results <- PhenoAligner_KNN(bcell,bcell_marker,cell_type="bcell")

bcell_pheno_result <- PhenoAligner_index(bcell_PA_knn_results$sce.others, bcell_PA_knn_results$sce.mt, bcell_PA_knn_results$coldata.mt, 
                               cell_type="bcell", cor_cutoff=0.6)



bcell_pheno_shuffle.list <- PhenoAligner_shuffle(sce.others <- bcell_PA_knn_results$sce.others,
                     sce.mt <- bcell_PA_knn_results$sce.mt,
                     cell_type="bcell",threads=20)



# bcell_pheno_result <- read.csv(paste0("processed_data/data_B2-19/PhenoAligner/tcell/", "bcell", "/PhenoAligner_index_final.csv"))
# bcell_pheno_shuffle.list <- readRDS(paste0("processed_data/data_B2-19/PhenoAligner/", "bcell", "/pheno_shuffle.list.rds"))

bcell_plot_pheno_list <- plot_pheno(bcell_pheno_result,bcell_pheno_shuffle.list,cell_type="bcell")

names(bcell_plot_pheno_list)

bcell_plot_pheno_list$`Low quality` <- NULL
names(bcell_plot_pheno_list)

for(subtype in names(bcell_plot_pheno_list)){
    bcell_plot_pheno_list[[subtype]]$celltype_sub <- subtype
}
plot_subtypes_df <- do.call(rbind, bcell_plot_pheno_list)

options(repr.plot.width=8, repr.plot.height=9)
p <- ggplot(plot_subtypes_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 2)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 5) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p)   





# old results for old cell typing
for(subtype in names(bcell_plot_pheno_list)){
    bcell_plot_pheno_list[[subtype]]$celltype_sub <- subtype
}
plot_subtypes_df <- do.call(rbind, bcell_plot_pheno_list)

options(repr.plot.width=8, repr.plot.height=9)
p <- ggplot(plot_subtypes_df, aes(x=Tissue, y=frac_shuffle,fill=Tissue)) + 
  geom_violin(trim=FALSE,na.rm = TRUE, scale = "width")+ 
  geom_point(aes(y = I_phenoaligner), size = 2)+
  geom_text(aes(y = I_phenoaligner+0.05 , label = paste0("N=", cells)), size = 3)+
  geom_text(aes(y = I_phenoaligner-0.1, label = significance), size = 5) +
  facet_wrap(. ~  celltype_sub, ncol = 3) +
  labs(title="",x="Tissue", y = "I_phenoaligner")+
  scale_y_continuous(limits = c(-0.05, 1.05))+
  theme_classic()
plot(p)   


