library(Seurat)
library(tidyverse)
library(magrittr)
library(monocle)

packageVersion("monocle")

set.seed=0

GC_plasma_use <- readRDS("processed_data/data_B2-19/monocle/GC_plasma_use.rds")

plasma_markers <- read.csv("processed_data/data_B2-19/cell_typing/bcell/plasma_monocle_markers.csv", row.names = 1)
#select gene set(here we used marker genes generated by Seurat FindAllMarkers() function)
plasma_markers <- plasma_markers[plasma_markers$p_val_adj < 0.05 & plasma_markers$avg_log2FC>0.5,]
head(plasma_markers)
length(unique(plasma_markers$gene))

GC_plasma_use$cell_type <- as.character(GC_plasma_use$cell_type)
table(GC_plasma_use$cell_type)

DefaultAssay(GC_plasma_use)

cds_plasma <- as.CellDataSet(GC_plasma_use)
cds_plasma <- estimateSizeFactors(cds_plasma)
cds_plasma <- estimateDispersions(cds_plasma)


sel.gene <- as.character(unique(plasma_markers$gene)) 
cds_plasma <- monocle::setOrderingFilter(cds_plasma, sel.gene)

## dimension reduciton
cds_plasma <- monocle::reduceDimension(cds_plasma, method = 'DDRTree')


## ordering cells
cds_plasma <- monocle::orderCells(cds_plasma)

gc()

# pdf("monocle/plasma_all.pdf")
options(repr.plot.width=6, repr.plot.height=4)
monocle::plot_cell_trajectory(cds_plasma, color_by = "cell_type") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "Pseudotime")
# dev.off()

unique(cds_plasma$State)

## ordering cells by assigning root nodes
GM_state <- function(cds_plasma){
  if (length(unique(cds_plasma$State)) > 1){
    T0_counts <- table(cds_plasma$State, cds_plasma$cell_type)[,"STMN1+ Plasmablast"]
    return(as.numeric(names(T0_counts)[which
                                       (T0_counts == max(T0_counts))]))
  } else {
    return (1)
  }
}
cds_plasma <- monocle::orderCells(cds_plasma, root_state =  GM_state(cds_plasma))

# pdf("monocle/plasma_all.pdf")
plot_cell_trajectory(cds_plasma, color_by = "cell_type") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "Pseudotime")
monocle::plot_cell_trajectory(cds_plasma, color_by = "State") 

# dev.off()

monocle::plot_cell_trajectory(cds_plasma, color_by = "cell_type")  + facet_wrap(~LN_condition)

monocle::plot_cell_trajectory(cds_plasma, color_by = "cell_type")  + facet_wrap(~cell_type)



pdf("processed_data/data_B2-19/monocle/plasma_self_markers_root.pdf")
monocle::plot_cell_trajectory(cds_plasma, color_by = "cell_type") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "State") 
monocle::plot_cell_trajectory(cds_plasma, color_by = "Pseudotime")
dev.off()

cds_plasma



c("MKI67","JCHAIN","IGHA1","IGHG1","IGHM","IGHD","ICOSLG","IL10") %in% 
rownames(cds_plasma@featureData)
#cytotoxic genes 

# check gene expression along pseudotime #cytotoxic genes 
my_genes <- c("MKI67","JCHAIN","IGHA1","IGHG1","IGHM","IGHD")
cds_plasma_subset <- cds_plasma[my_genes,]
plot_genes_in_pseudotime(cds_plasma_subset, color_by = "cell_type")

saveRDS(cds_plasma, "processed_data/data_B2-19/monocle/plasma_self_markers_root.rds")

# cds_plasma <- readRDS("processed_data/data_B2-19/monocle/plasma_self_markers_root.rds")

# fig
options(repr.plot.width=6, repr.plot.height=5)
my_genes <- c("MKI67","IGHA1","IGHG1","IGHM")
cds_plasma_subset <- cds_plasma[my_genes,]
plot_genes_in_pseudotime(cds_plasma_subset, color_by = "cell_type",ncol = 2)

options(repr.plot.width=6, repr.plot.height=4)
plot_cell_trajectory(cds_plasma, color_by = "cell_type")+ theme(legend.position="right")
monocle::plot_cell_trajectory(cds_plasma, color_by = "Pseudotime")+ theme(legend.position="right")

GC_nk_use <- readRDS("processed_data/data_B2-19/monocle/GC_nk_use.rds")

table(GC_nk_use$cell_type)

nk_markers <- read.csv("processed_data/data_B2-19/cell_typing/tcell/NK_monocle_markers.csv", row.names = 1)
#select gene set(here we used marker genes generated by Seurat FindAllMarkers() function)
nk_markers <- nk_markers[nk_markers$p_val_adj < 0.05 & nk_markers$avg_log2FC > 0.5,]
head(nk_markers)
length(unique(nk_markers$gene))

cds_nk <- as.CellDataSet(GC_nk_use)
cds_nk <- estimateSizeFactors(cds_nk)
cds_nk <- estimateDispersions(cds_nk)

sel.gene <- unique(nk_markers$gene)
cds_nk <- monocle::setOrderingFilter(cds_nk, sel.gene)

## dimension reduciton
cds_nk <- monocle::reduceDimension(cds_nk, method = 'DDRTree')

## ordering cells
cds_nk <- monocle::orderCells(cds_nk)

gc()

# pdf("monocle/tcell_all.pdf")
options(repr.plot.width=8, repr.plot.height=7)
monocle::plot_cell_trajectory(cds_nk, color_by = "cell_type") 
monocle::plot_cell_trajectory(cds_nk, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_nk, color_by = "Pseudotime")
# dev.off()

## ordering cells by assigning root nodes
GM_state <- function(cds_nk){
  if (length(unique(cds_nk$State)) > 1){
    T0_counts <- table(cds_nk$State, cds_nk$cell_type)[,"NK3"]
    return(as.numeric(names(T0_counts)[which
                                       (T0_counts == max(T0_counts))]))
  } else {
    return (1)
  }
}
cds_nk <- monocle::orderCells(cds_nk, root_state =  GM_state(cds_nk))

# pdf("monocle/nk_all.pdf")
plot_cell_trajectory(cds_nk, color_by = "cell_type") 
monocle::plot_cell_trajectory(cds_nk, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_nk, color_by = "Pseudotime")
plot_cell_trajectory(cds_nk, color_by = "State") 

# dev.off()

monocle::plot_cell_trajectory(cds_nk, color_by = "cell_type")  + facet_wrap(~LN_condition)

monocle::plot_cell_trajectory(cds_nk, color_by = "cell_type")  + facet_wrap(~cell_type)

pdf("processed_data/data_B2-19/monocle/nk_self_markers_root.pdf")
monocle::plot_cell_trajectory(cds_nk, color_by = "cell_type") 
monocle::plot_cell_trajectory(cds_nk, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_nk, color_by = "State") 
monocle::plot_cell_trajectory(cds_nk, color_by = "Pseudotime")
dev.off()

cds_nk

saveRDS(cds_nk, "processed_data/data_B2-19/monocle/nk_self_markers_root.rds")

cds_nk <- readRDS("processed_data/data_B2-19/monocle/nk_self_markers_root.rds")

# pdf("monocle/nk_all.pdf")
options(repr.plot.width=4, repr.plot.height=4)
plot_cell_trajectory(cds_nk, color_by = "cell_type") 
# monocle::plot_cell_trajectory(cds_nk, color_by = "LN_condition") 
monocle::plot_cell_trajectory(cds_nk, color_by = "Pseudotime")
# dev.off()

# monocle::plot_cell_trajectory(cds_nk, color_by = "Pseudotime") +
#   scale_color_gradient(low = "#89afd2", high = "#ef8775")

# cds_nk <- readRDS("processed_data/data_B2-19/monocle/nk_self_markers_root.rds")

# branch analysis ---------------------------------------------------------
BEAM_res <- BEAM(cds_nk, branch_point = 1, cores =30)
BEAM_res <- BEAM_res[order(BEAM_res$qval),]
BEAM_res <- BEAM_res[,c("gene_short_name", "pval", "qval")]

saveRDS(BEAM_res, "processed_data/data_B2-19/monocle/nk_self_markers_BEAM.rds")

head(BEAM_res)

summary(BEAM_res$qval)

table(BEAM_res$qval<1e-50)
# qnorm(0.001, mean(BEAM_res$qval), sd(BEAM_res$qval))

plot_genes_branched_heatmap(cds_nk[row.names(subset(BEAM_res,
                                                  qval<1e-50)),],
                            branch_point = 1,
                            num_clusters = 6,
                            cores = 20,
                            use_gene_short_name = T,
                            show_rownames = T)

cds_nk_genes <- row.names(subset(fData(cds_nk),
                               gene_short_name %in% c("IFNG","GZMB", "GZMK", "NKG7", "PRF1", "GZMA", "GZMH")))#cytotoxic genes 
plot_genes_branched_pseudotime(cds_nk[cds_nk_genes,],
                               branch_point = 1,
                               color_by = "cell_type",
                               ncol = 3)

cds_nk_genes <- row.names(subset(fData(cds_nk),
                               gene_short_name %in% c("IFNG","GZMB", "GZMK", "GZMH","CCL5", "FCGR3A", "XCL1")))
plot_genes_branched_pseudotime(cds_nk[cds_nk_genes,],
                               branch_point = 1,
                               color_by = "cell_type",
                               ncol = 3)



# 提前停止脚本执行
return()



GC_plasma <-readRDS("processed_data/data_B2-19/cell_typing/bcell/plasma.batch.corrected_ct_0.5.rds")
meta_condition <- read.csv("processed_data/data_B2-19/metadata_all_ct_subtype_condition_noTLB.csv", row.names = 1)

meta <- meta_condition[colnames(GC_plasma),]
all(rownames(meta)==colnames(GC_plasma))
GC_plasma$LN_condition <- meta$LN_condition

table(GC_plasma$cell_type)

Idents(GC_plasma) <- "cell_type"
table(Idents(GC_plasma))

# plasma_markers <- FindAllMarkers(GC_plasma, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
# write.csv(plasma_markers, "processed_data/data_B2-19/cell_typing/bcell/plasma_monocle_markers.csv")

# subset big subtype to 500 cells
set.seed=0
cell_use <- NULL
for(subtype in unique(GC_plasma$cell_type)){
    print(subtype)
    print(sum(GC_plasma$cell_type==subtype))
    if(sum(GC_plasma$cell_type==subtype) > 500){
        rowname <- sample(colnames(GC_plasma)[GC_plasma$cell_type==subtype], 500, replace = FALSE)
    }else{
        rowname <- colnames(GC_plasma)[GC_plasma$cell_type==subtype]
    }
    cell_use <- c(cell_use,rowname)
    print(length(cell_use))
}

GC_plasma_use <- subset(GC_plasma,cells=cell_use)

saveRDS(GC_plasma_use, "processed_data/data_B2-19/monocle/GC_plasma_use.rds")

GC_tcell <-readRDS("plots/data/tcell_no_TLB_new_meta.rds")

GC_NK <- subset(GC_tcell,subset= subtype1 %in% c("NK1","NK2","NK3"))

GC_NK$cell_type <- GC_NK$subtype1
Idents(GC_NK) <- "cell_type"
table(GC_NK$cell_type)

# nk_markers <- FindAllMarkers(GC_NK, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
# write.csv(nk_markers, "processed_data/data_B2-19/cell_typing/tcell/NK_monocle_markers.csv")

# subset big subtype to 1000 cells
set.seed=0
nk_use <- NULL
for(subtype in unique(GC_NK$cell_type)){
    print(subtype)
    print(sum(GC_NK$cell_type==subtype))
    if(sum(GC_NK$cell_type==subtype) > 1000){
        rowname <- sample(colnames(GC_NK)[GC_NK$cell_type==subtype], 1000, replace = FALSE)
    }else{
        rowname <- colnames(GC_NK)[GC_NK$cell_type==subtype]
    }
    nk_use <- c(nk_use,rowname)
    print(length(rowname))
}
GC_nk_use <- subset(GC_NK,cells=nk_use)

GC_nk_use$cell_type <- as.character(GC_nk_use$cell_type)
table(GC_nk_use$cell_type)
DefaultAssay(GC_nk_use) <- "RNA"

saveRDS(GC_nk_use, "processed_data/data_B2-19/monocle/GC_nk_use.rds")


